# -*- coding: utf-8 -*-
"""preblock/coin

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ubcBvowCm93k1AkuIOm2i4-kgsAnqsIj
"""

def tosses(n):
    """Generates all possible combinations of heads and tails for n coin tosses.

    Args:
        n (int): The number of coin tosses.

    Returns:
        list[str]: All possible H/T strings of length n.
    """
    if n == 0:
        return [""]

    results = []
    for t in tosses(n - 1):
        results.append("H" + t)
        results.append("T" + t)
    return results


if __name__ == "__main__":
    print(tosses(3))